CREATE TABLE RIODS.GIT_COMMIT (
	COMMENT VARCHAR(1024),
    -- 2083 is the maximum length of urls supported by IE, and general
    -- consensus among developers is that this should be used as a maximum
    -- length of general urls
	URL VARCHAR(2083) NOT NULL,
	COMMITER_EMAIL VARCHAR(512),
	COMMITER_NAME VARCHAR(512),
	COMMIT_DATE TIMESTAMP,
    LINK_URL VARCHAR(2083),
	-- uuids are always 128-bit by specification
    -- 36 characters for string representation are defined in the corresponding
    -- RFC: https://tools.ietf.org/html/rfc4122#section-3
    -- However, EXTERNAL_KEY2, where it is used in the RIODS database, are
    -- always defined as CHAR(40). We adhere to this convention
    LINKED_FROM CHAR(40),
	REPOSITORY_KEY VARCHAR(1024),
    -- sha hashes are 40 hex symbols, but it is now possible to choose different
    -- hash algorithms for git (custom configuration)
	SHA VARCHAR(100) NOT NULL,
    -- short sha is currently at 7 symbols, but let's take 12 for good measure
    -- yeah, this could also just be on the view and then selected via sql,
    -- but maybe that is a problem for future me.
	SHORT_SHA VARCHAR(12) NOT NULL,
    -- Reference to the project area this git commit has been linked from. This
    -- will lead to identical commits being stored twice if they are linked
    -- from work items in seperate PAs. However, this is necessary for only
    -- showing commits from project areas that the reporting builder user is
    -- allowed to see.
    PROJECT_ID INTEGER DEFAULT -1 NOT NULL,
    -- primary key is not allowed to be autogenerated, but instead needs to be
    -- labeled as a surrogate key in the ttl file. This will then generate pks
    -- when the dcc job runs. Additional abstraction layer.
	ID_PK INTEGER NOT NULL, 
	CONSTRAINT GIT_COMMIT_PK PRIMARY KEY (ID_PK),
    CONSTRAINT PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES RIODS.PROJECT(PROJECT_ID)
);
