CREATE TABLE RIODS.GIT_ISSUE_ASSIGNEE(
	ASSIGNEE_ID INTEGER NOT NULL,
	ISSUE_ID INTEGER NOT NULL,
	CONSTRAINT GIT_ISSUE_ASSIGNEE_PK PRIMARY KEY (ASSIGNEE_ID, ISSUE_ID),
	CONSTRAINT GIT_ISSUE_ASSIGNEE_GIT_ISSUE_FK FOREIGN KEY (ISSUE_ID) REFERENCES RIODS.GIT_ISSUE(ID_PK),
	CONSTRAINT GIT_ISSUE_ASSIGNEE_RESOURCE_FK FOREIGN KEY (ASSIGNEE_ID) REFERENCES RIODS.RESOURCE(RESOURCE_ID)
);
