CREATE TABLE RIODS.GIT_MERGE_REQUEST_RELATION (
    MERGE_REQUEST_ID INTEGER NOT NULL,
    REQUEST_ID INTEGER NOT NULL,
    PROJECT_ID INTEGER NOT NULL,
    CONSTRAINT GIT_MERGE_REQUEST_RELATION_PK PRIMARY KEY (MERGE_REQUEST_ID, REQUEST_ID, PROJECT_ID),
    CONSTRAINT GIT_MERGE_REQUEST_RELATION_MERGE_REQUEST_FK FOREIGN KEY (MERGE_REQUEST_ID) REFERENCES RIODS.GIT_MERGE_REQUEST(ID_PK),
    CONSTRAINT GIT_MERGE_REQUEST_RELATION_REQUEST_FK FOREIGN KEY (REQUEST_ID) REFERENCES RIODS.REQUEST(REQUEST_ID),
    CONSTRAINT GIT_MERGE_REQUEST_RELATION_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES RIODS.PROJECT(PROJECT_ID)
);
