-- drop commit views
DROP VIEW RIDW.VW_GIT_COMMIT_LOOKUP;
DROP VIEW RIDW.VW_GIT_COMMIT;
-- drop commit schemas
DROP TABLE RIODS.GIT_COMMIT_LOOKUP;
DROP TABLE RIODS.GIT_COMMIT;
-- drop issue views
DROP VIEW RIDW.VW_GIT_ISSUE_ASSIGNEE;
DROP VIEW RIDW.VW_GIT_ISSUE_RELATION;
DROP VIEW RIDW.VW_GIT_ISSUE;
-- drop issue schemas
DROP TABLE RIODS.GIT_ISSUE_ASSIGNEE;
DROP TABLE RIODS.GIT_ISSUE_RELATION;
DROP TABLE RIODS.GIT_ISSUE;
-- drop merge request views
DROP VIEW RIDW.VW_MERGE_REQUEST_ASSIGNEE;
DROP VIEW RIDW.VW_MERGE_REQUEST_RELATION;
DROP VIEW RIDW.VW_MERGE_REQUEST;
-- drop merge request schemas
DROP TABLE RIODS.MERGE_REQUEST_ASSIGNEE;
DROP TABLE RIODS.MERGE_REQUEST_RELATION;
DROP TABLE RIODS.MERGE_REQUEST;
