CREATE VIEW RIDW.VW_GIT_COMMIT_LOOKUP (
    REQUEST_ID,
    REQUEST_NAME,
    COMMIT_ID,
    COMMIT_COMMENT
) AS (SELECT
    R.REQUEST_ID,
    R.NAME AS REQUEST_NAME,
    C.ID_PK,
    C.COMMENT AS COMMIT_COMMENT
FROM
    RIODS.GIT_COMMIT_LOOKUP LU
    JOIN RIODS.REQUEST R ON R.REQUEST_ID = LU.REQUEST_ID
    JOIN RIODS.GIT_COMMIT C ON C.ID_PK = LU.COMMIT_ID
);
